CREATE TABLE
    IF NOT EXISTS characters (id PRIMARY KEY, name TEXT, size TEXT);

INSERT INTO
    characters (id, name, size)
VALUES
    (0, 'Mario', 'M'),
    (1, 'Baby Peach', 'S'),
    (2, 'Waluigi', 'L'),
    (3, 'Bowser', 'L'),
    (4, 'Baby Daisy', 'S'),
    (5, 'Dry Bones', 'S'),
    (6, 'Baby Mario', 'S'),
    (7, 'Luigi', 'M'),
    (8, 'Toad', 'S'),
    (9, 'Donkey Kong', 'L'),
    (10, 'Yoshi', 'M'),
    (11, 'Wario', 'L'),
    (12, 'Baby Luigi', 'S'),
    (13, 'Toadette', 'S'),
    (14, 'Koopa Troopa', 'S'),
    (15, 'Daisy', 'M'),
    (16, 'Peach', 'M'),
    (17, 'Birdo', 'M'),
    (18, 'Diddy Kong', 'M'),
    (19, 'King Boo', 'L'),
    (20, 'Bowser Jr.', 'M'),
    (21, 'Dry Bowser', 'L'),
    (22, 'Funky Kong', 'L'),
    (23, 'Rosalina', 'L'),
    (24, 'Small Mii Outfit A (Male)', 'S'),
    (25, 'Small Mii Outfit A (Female)', 'S'),
    (26, 'Small Mii Outfit B (Male)', 'S'),
    (27, 'Small Mii Outfit B (Female)', 'S'),
    (28, 'Small Mii Outfit C (Male)', 'S'),
    (29, 'Small Mii Outfit C (Female)', 'S'),
    (30, 'Medium Mii Outfit A (Male)', 'M'),
    (31, 'Medium Mii Outfit A (Female)', 'M'),
    (32, 'Medium Mii Outfit B (Male)', 'M'),
    (33, 'Medium Mii Outfit B (Female)', 'M'),
    (34, 'Medium Mii Outfit C (Male)', 'M'),
    (35, 'Medium Mii Outfit C (Female)', 'M'),
    (36, 'Large Mii Outfit A (Male)', 'L'),
    (37, 'Large Mii Outfit A (Female)', 'L'),
    (38, 'Large Mii Outfit B (Male)', 'L'),
    (39, 'Large Mii Outfit B (Female)', 'L'),
    (40, 'Large Mii Outfit C (Male)', 'L'),
    (41, 'Large Mii Outfit C (Female)', 'L'),
    (42, 'Medium Mii', 'M'),
    (43, 'Small Mii', 'S'),
    (44, 'Large Mii', 'L'),
    (45, 'Peach (Character/Vehicle Selection)', 'M'),
    (46, 'Daisy (Character/Vehicle Selection)', 'M'),
    (47, 'Rosalina (Character/Vehicle Selection)', 'L');

-- DROP TABLE characters