CREATE TABLE
    IF NOT EXISTS characters (name TEXT PRIMARY KEY, size TEXT);

INSERT INTO
    characters (name, size)
VALUES
    ('Baby Mario', 'S'),
    ('Baby Luigi', 'S'),
    ('Baby Peach', 'S'),
    ('Baby Daisy', 'S'),
    ('Toad', 'S'),
    ('Toadette', 'S'),
    ('Koopa Troopa', 'S'),
    ('Dry Bones', 'S'),
    ('Mario', 'M'),
    ('Luigi', 'M'),
    ('Peach', 'M'),
    ('Daisy', 'M'),
    ('Yoshi', 'M'),
    ('Birdo', 'M'),
    ('Diddy Kong', 'M'),
    ('Bowser Jr', 'M'),
    ('Wario', 'L'),
    ('Waluigi', 'L'),
    ('Donkey Kong', 'L'),
    ('Funky Kong', 'L'),
    ('Bowser', 'L'),
    ('King Boo', 'L'),
    ('Rosalina', 'L'),
    ('Dry Bowser', 'L'),
    ('Medium Mii', 'M'),
    ('Small Mii', 'S'),
    ('Large Mii', 'L'),
    ('Small Mii Outfit A (Male)', 'S'),
    ('Small Mii Outfit A (Female)', 'S'),
    ('Small Mii Outfit B (Male)', 'S'),
    ('Small Mii Outfit B (Female)', 'S'),
    ('Small Mii Outfit C (Male)', 'S'),
    ('Small Mii Outfit C (Female)', 'S'),
    ('Medium Mii Outfit A (Male)', 'M'),
    ('Medium Mii Outfit A (Female)', 'M'),
    ('Medium Mii Outfit B (Male)', 'M'),
    ('Medium Mii Outfit B (Female)', 'M'),
    ('Medium Mii Outfit C (Male)', 'M'),
    ('Medium Mii Outfit C (Female)', 'M'),
    ('Large Mii Outfit A (Male)', 'L'),
    ('Large Mii Outfit A (Female)', 'L'),
    ('Large Mii Outfit B (Male)', 'L'),
    ('Large Mii Outfit B (Female)', 'L'),
    ('Large Mii Outfit C (Male)', 'L'),
    ('Large Mii Outfit C (Female)', 'L')
    -- DROP TABLE characters