CREATE TABLE
    IF NOT EXISTS regular (track TEXT);

INSERT INTO
    regular (track)
VALUES
    ('Wii Mushroom Gorge'),
    ('Tour Choco Mountain'),
    ('DS Luigi''s Mansion'),
    ('Wii Daisy Circuit'),
    ('Goomba Circuit'),
    ('Eventide Gorge'),
    ('Quaking Mad Cliffs'),
    ('Toad''s Temple'),
    ('DS DK Pass'),
    ('Wii Koopa Cape'),
    ('GBA Bowser Castle 2'),
    ('GCN Dino Dino Jungle'),
    ('Musical Cliff'),
    ('Desert Fort'),
    ('Camp Kartigan'),
    ('Fort Francis'),
    ('GCN Waluigi Stadium'),
    ('DS Peach Gardens'),
    ('Wii Grumble Volcano'),
    ('SNES Bowser Castle 2'),
    ('Glacier Mine'),
    ('Tau-Cryovolcano'),
    ('Phendrana Frostbite'),
    ('Siberian Chateau'),
    ('N64 Sherbet Land'),
    ('Wii DK Summit'),
    ('3DS Music Park'),
    ('GCN DK Mountain'),
    ('Super Marine World'),
    ('Frantic Funyard'),
    ('Honeybee Hideout'),
    ('Stickerbush Serenity'),
    ('GCN Daisy Cruiser'),
    ('N64 Banshee Boardwalk'),
    ('DS Waluigi Pinball'),
    ('Wii Wario''s Gold Mine'),
    ('Coin Heaven'),
    ('The Grand Archives'),
    ('Midnight Museum'),
    ('Shy Guy Lumber Co.'),
    ('SNES Choco Island 2'),
    ('Wii Coconut Mall'),
    ('GBA Bowser Castle 3'),
    ('GCN Yoshi Circuit'),
    ('BKMR Moai Mountain'),
    ('Ice Cream Fortress'),
    ('Kitayama Keep'),
    ('Bowser Jr.''s Crafty Castle'),
    ('DS Wario Stadium'),
    ('Wii Toad''s Factory'),
    ('3DS DK Jungle'),
    ('N64 Bowser''s Castle'),
    ('Terra Ursae'),
    ('Inferni Umbra'),
    ('Darkness Tempe'),
    ('Blooper Ruins'),
    ('3DS Neo Bowser City'),
    ('Wii Moonview Highway'),
    ('DS Airship Fortress'),
    ('N64 Wario Stadium'),
    ('Bluster Blob Bluff'),
    ('Poisonous Pass'),
    ('The Great Apple War'),
    ('Ruinated Peach''s Castle'),
    ('N64 DK''s Jungle Parkway'),
    ('DS Delfino Square'),
    ('Wii Maple Treeway'),
    ('Tour Bowser Castle 3'),
    ('Sandstone Cliffs'),
    ('Windy Whirl'),
    ('Volcanic Skyway'),
    ('Castle in the Sky'),
    ('Wii Dry Dry Ruins'),
    ('DS Tick-Tock Clock'),
    ('GBA Bowser Castle 4'),
    ('SNES Rainbow Road'),
    ('Banished Keep'),
    ('Thump Bump Forest'),
    ('Obstagoon''s Palace'),
    ('Cruel Angel''s Thesis'),
    ('3DS Wario Shipyard'),
    ('GBA Boo Lake'),
    ('Wii Bowser''s Castle'),
    ('N64 Rainbow Road'),
    ('Ghostly Gulch'),
    ('Spooky Swamp'),
    ('Northern Heights'),
    ('Vile Isle'),
    ('3DS Maka Wuhu'),
    ('GCN Sherbet Land'),
    ('DS Bowser''s Castle'),
    ('Wii Rainbow Road'),
    ('Cosmic Causeway'),
    ('Aqua Dungeon'),
    ('Garden of Dreams'),
    ('Bowser''s Termination Station');