CREATE TABLE
    IF NOT EXISTS tracks (name TEXT, cup TEXT);

INSERT INTO
    tracks (name, cup)
VALUES
    ('Wii Mushroom Gorge', 'MUSHROOM CUP'),
    ('Tour Choco Mountain', 'MUSHROOM CUP'),
    ('DS Luigi''s Mansion', 'MUSHROOM CUP'),
    ('Wii Daisy Circuit', 'MUSHROOM CUP'),
    ('Goomba Circuit', '1-UP CUP'),
    ('Eventide Gorge', '1-UP CUP'),
    ('Quaking Mad Cliffs', '1-UP CUP'),
    ('Toad''s Temple', '1-UP CUP'),
    ('DS DK Pass', 'GREEN SHELL CUP'),
    ('Wii Koopa Cape', 'GREEN SHELL CUP'),
    ('GBA Bowser Castle 2', 'GREEN SHELL CUP'),
    ('GCN Dino Dino Jungle', 'GREEN SHELL CUP'),
    ('Musical Cliff', 'RED SHELL CUP'),
    ('Desert Fort', 'RED SHELL CUP'),
    ('Camp Kartigan', 'RED SHELL CUP'),
    ('Fort Francis', 'RED SHELL CUP'),
    ('GCN Waluigi Stadium', 'FIRE FLOWER CUP'),
    ('DS Peach Gardens', 'FIRE FLOWER CUP'),
    ('Wii Grumble Volcano', 'FIRE FLOWER CUP'),
    ('SNES Bowser Castle 2', 'FIRE FLOWER CUP'),
    ('Glacier Mine', 'ICE FLOWER CUP'),
    ('Tau-Cryovolcano', 'ICE FLOWER CUP'),
    ('Phendrana Frostbite', 'ICE FLOWER CUP'),
    ('Siberian Chateau', 'ICE FLOWER CUP'),
    ('N64 Sherbet Land', 'BANANA CUP'),
    ('Wii DK Summit', 'BANANA CUP'),
    ('3DS Music Park', 'BANANA CUP'),
    ('GCN DK Mountain', 'BANANA CUP'),
    ('Super Marine World', 'BANANA BUNCH CUP'),
    ('Frantic Funyard', 'BANANA BUNCH CUP'),
    ('Honeybee Hideout', 'BANANA BUNCH CUP'),
    ('Stickerbush Serenity', 'BANANA BUNCH CUP'),
    ('GCN Daisy Cruiser', 'COIN CUP'),
    ('N64 Banshee Boardwalk', 'COIN CUP'),
    ('DS Waluigi Pinball', 'COIN CUP'),
    ('Wii Wario''s Gold Mine', 'COIN CUP'),
    ('Coin Heaven', 'PURPLE COIN CUP'),
    ('The Grand Archives', 'PURPLE COIN CUP'),
    ('Midnight Museum', 'PURPLE COIN CUP'),
    ('Shy Guy Lumber Co.', 'PURPLE COIN CUP'),
    ('SNES Choco Island 2', 'YOSHI EGG CUP'),
    ('Wii Coconut Mall', 'YOSHI EGG CUP'),
    ('GBA Bowser Castle 3', 'YOSHI EGG CUP'),
    ('GCN Yoshi Circuit', 'YOSHI EGG CUP'),
    ('BKMR Moai Mountain', 'BIRDO EGG CUP'),
    ('Ice Cream Fortress', 'BIRDO EGG CUP'),
    ('Kitayama Keep', 'BIRDO EGG CUP'),
    ('Bowser Jr.''s Crafty Castle', 'BIRDO EGG CUP'),
    ('DS Wario Stadium', 'BLOCK CUP'),
    ('Wii Toad''s Factory', 'BLOCK CUP'),
    ('3DS DK Jungle', 'BLOCK CUP'),
    ('N64 Bowser''s Castle', 'BLOCK CUP'),
    ('Terra Ursae', 'BRICK CUP'),
    ('Inferni Umbra', 'BRICK CUP'),
    ('Darkness Tempe', 'BRICK CUP'),
    ('Blooper Ruins', 'BRICK CUP'),
    ('3DS Neo Bowser City', 'BOMB CUP'),
    ('Wii Moonview Highway', 'BOMB CUP'),
    ('DS Airship Fortress', 'BOMB CUP'),
    ('N64 Wario Stadium', 'BOMB CUP'),
    ('Bluster Blob Bluff', 'BUDDY CUP'),
    ('Poisonous Pass', 'BUDDY CUP'),
    ('The Great Apple War', 'BUDDY CUP'),
    ('Ruinated Peach''s Castle', 'BUDDY CUP'),
    ('N64 DK''s Jungle Parkway', 'LEAF CUP'),
    ('DS Delfino Square', 'LEAF CUP'),
    ('Wii Maple Treeway', 'LEAF CUP'),
    ('Tour Bowser Castle 3', 'LEAF CUP'),
    ('Sandstone Cliffs', 'FEATHER CUP'),
    ('Windy Whirl', 'FEATHER CUP'),
    ('Volcanic Skyway', 'FEATHER CUP'),
    ('Castle in the Sky', 'FEATHER CUP'),
    ('Wii Dry Dry Ruins', 'STAR CUP'),
    ('DS Tick-Tock Clock', 'STAR CUP'),
    ('GBA Bowser Castle 4', 'STAR CUP'),
    ('SNES Rainbow Road', 'STAR CUP'),
    ('Banished Keep', 'ZTAR CUP'),
    ('Thump Bump Forest', 'ZTAR CUP'),
    ('Obstagoon''s Palace', 'ZTAR CUP'),
    ('Cruel Angel''s Thesis', 'ZTAR CUP'),
    ('3DS Wario Shipyard', 'LIGHTNING CUP'),
    ('GBA Boo Lake', 'LIGHTNING CUP'),
    ('Wii Bowser''s Castle', 'LIGHTNING CUP'),
    ('N64 Rainbow Road', 'LIGHTNING CUP'),
    ('Ghostly Gulch', 'THUNDER CUP'),
    ('Spooky Swamp', 'THUNDER CUP'),
    ('Northern Heights', 'THUNDER CUP'),
    ('Vile Isle', 'THUNDER CUP'),
    ('3DS Maka Wuhu', 'SPECIAL CUP'),
    ('GCN Sherbet Land', 'SPECIAL CUP'),
    ('DS Bowser''s Castle', 'SPECIAL CUP'),
    ('Wii Rainbow Road', 'SPECIAL CUP'),
    ('Cosmic Causeway', 'RAINBOW CUP'),
    ('Aqua Dungeon', 'RAINBOW CUP'),
    ('Garden of Dreams', 'RAINBOW CUP'),
    ('Bowser''s Termination Station', 'RAINBOW CUP');